eureka:
    client:
        service-url:
            defaultZone: http://127.0.0.1:8761/eureka/

server:
    port: 8081
    
spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
        username: root
    jpa:
        show-sql: true
    redis:
        host: localhost
        port: 6379
env:
    test

girl:
  name: lili
  age: 26
